### ISSUE TITLE
Label ver 0.20 of this package as broken

### ISSUE THREAD

**Issue by igortg** [conda-forge/serialchemy-feedstock#3]
Hi @conda-forge/core,

Can you please move ver. 0.20 of this package from ``main`` to ``broken`` on the conda-forge channel? Reason: v. 0.20 was published by mistake

**Comment by igortg** [comment]
Maintainers (@lincrosenbach, @nicoddemus), please confirm

**Comment by nicoddemus** [comment]
Sure

**Comment by ocefpaf** [comment]
> Hi @conda-forge/core,
> 
> Can you please move ver. 0.20 of this package from `main` to `broken` on the conda-forge channel? Reason: v. 0.20 was published by mistake

Done. Please check if I got ir right: https://anaconda.org/conda-forge/serialchemy/files?channel=broken

**Comment by nicoddemus** [comment]
Unfortunately it is the `0.20.0` version that is broken, not `0.2.0`. 😁

**Comment by ocefpaf** [comment]
> Unfortunately it is the `0.20.0` version that is broken, not `0.2.0`.

Oops. Fixed it! Can you double check: https://anaconda.org/conda-forge/serialchemy/files

**Comment by nicoddemus** [comment]
Great, thanks!
